name: Breakroom
options:
  bundleIdPrefix: com.cherryblossomdev
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "26.2"
  generateEmptyDirectories: true

packages:
  SocketIO:
    url: https://github.com/socketio/socket.io-client-swift
    exactVersion: 16.1.1

settings:
  base:
    SWIFT_VERSION: "6.0"

targets:
  Breakroom:
    type: application
    platform: iOS
    sources:
      - Breakroom
    dependencies:
      - package: SocketIO
        product: SocketIO
    settings:
      base:
        INFOPLIST_GENERATION_MODE: GeneratedFile
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_STYLE: Automatic
        PRODUCT_BUNDLE_IDENTIFIER: com.cherryblossomdev.Breakroom
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        DEVELOPMENT_ASSET_PATHS: "\"Breakroom/Preview Content\""
        ENABLE_PREVIEWS: YES
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        Release:
          SWIFT_COMPILATION_MODE: wholemodule
